#I will write later

name: my-first-workflow

on:
  pull_request:
    paths:
    - lint/
    - test/
  


jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Hello World lint"

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Hello World Test"

